#+title: Privacy Policy

LikeNow Business Machines Incorporated, a Delaware corporation respects your privacy. In that regard, we have created this Privacy Policy to let you know what information we collect when you visit the website likenow.app (the “Website”) and/or use our mobile applications and/or other services offered via our Website (collectively, the “Service”), why we collect it, and how it is used.
** Your Consent To This Privacy Policy

By using the Website or the Service, you agree to this Privacy Policy and the collection and use of information contemplated hereby. This is our entire and exclusive Privacy Policy and it supersedes any earlier version.

We may change this Privacy Policy by posting a new version of this Privacy Policy on our Website or through the Service, and it is your responsibility to review this policy periodically. When we do change the policy, we will also revise the “Revised” date and may notify you or post a message on the Website and/or through the Service. Your continued use of the Website or the Service constitutes your agreement to this Privacy Policy and any updates.
** What Information Does LikeNow Collect?

Personal Information. We collect, use, store and transfer different kinds of Personal Information about you. “Personal Information” means any information that may be used to identify, describe, or be reasonably linked to an individual or household. We may ask you to provide Personal Information that will enable us to enhance your use of the Service, for purposes such as facilitating correspondence with you, registering your entitlement to access certain special features, or to complete transactions. It is always your choice whether or not to provide that Personal Information. If you choose not to provide requested Personal Information, you may not be able to use certain features of the Service.

We have grouped together the following categories of Personal Information to explain how this type of information is used by us. These terms are used throughout this notice: ‍

- Identity Information, including your name, birthdate, age, social security number and any of the following pieces of information related to your spouse.
- Contact Information, including your home or other physical address, email address, and phone number.
- Financial Information, including your credit information and payment card details.
- Technical Information.

We may collect and use technical data and related information—including but not limited to technical information about your device(s), system and application software, and peripherals—that is gathered periodically to facilitate the provision of software updates, product support, and other services to you (if any) related to the Service. This information is referred to herein as Technical Information. We may also automatically receive and record information on our server logs from your browser, which could include your IP address, cookie information, browser information, and the page you request. A “cookie” is a text file that websites send to a visitor’s computer or other Internet-connected device to uniquely identify the visitor’s browser or to store information or settings in the browser. If you wish to disable the storage of cookies on your device, you may do so using the settings on your browser or device. Please note, however, that without cookies you may not be able to use all of the features of our websites. For more information on deleting or controlling cookies, visit www.aboutcookies.org.

- Location Based Information. You also acknowledge and agree that LikeNow Business Machines Incorporated may collect location-based data from you through the Service (“Location Based Information”). LikeNow owns this information.

** How Does LikeNow Collect Personal Information?

We use different methods to collect personal information from and about you, including through the channels set out below.

- Direct Interactions. You give us your Personal Information in your direct interactions with us. Such Personal Information includes Identity Information, Contact Information, Financial Information, and Technical Information which you give us from time to time (i) by using our Website; (ii) through other electronic platforms which we may offer or which we have agreed with you to use, (iii) by corresponding with us by email or post, or (iv) by speaking to us in person or over the telephone.
- Publicly Available Sources. We collect Personal Information from publicly availably sources, including from public registers.

** How Does LikeNow Use Personal Information?

Except as otherwise set forth herein, or in any applicable Terms of Service, Personal Information and Location Based Information that we collect will be used to support your relationship with LikeNow, Inc and our products and services or partners. Among other things, we want to help you quickly find information through our Service, populate forms and respond to requests for information, leverage our tools in connection with your authorized use of our products and services, process payment, facilitate interaction with third party services, and alert you to product upgrades, special offers, updated information and other new products and services from LikeNow, Inc.

When you want to resume your quoting process at a later point and maintain a session across devices, we may use the Personal Information that you provide to create “cross device” capabilities to enable you to retrieve your quotes and to access your profiles between devices.

We also use information to perform data analyses (including market and consumer research, trend analysis, financial analysis, and anonymization of Personal Information), protect against, identify and prevent fraud and other criminal activity, claims and other liabilities, and comply with and enforce applicable legal requirements, relevant industry standards and our policies.

LikeNow, Inc may use Location Based Information, as long as it is in a form that does not personally identify you, to improve, market or promote its products (including without limitation to comply with applicable laws or regulations related to insurance) or to provide services or technologies to you. LikeNow, Inc may also sell or license Location Based Information regarding its users to third parties, including Service Providers, but not in a manner in which the recipient will be able to identify you personally. You acknowledge that certain information or content that you provide in connection with the Service may inherently allow or help third parties to personally identify you.
** Sharing Of Personal Information
LikeNow may share Personal Information or Location Based Information it collects about you to or with third parties but only if we believe based upon your actions (including your actions and submissions via our Website) that you intend to interact with such Professionals through your use of our Service. This includes Professionals whose products or services may be marketed through channels outside of our Service. LikeNow Business Machines Incorporated does not sell your Personal information to other third parties. Unless you initiate a phone exchange with us, we will not contact you by telephone, and we will never share with third parties any telephone number(s) that you provide to us or that we may receive from third parties.

Agents or contractors of LikeNow may have access to your Personal Information and Location Based Information on a need-to-know basis for the purpose of performing services on behalf of LikeNow. All such agents or contractors who have access to such information are asked to keep the information confidential and not use it for any other purpose than to carry out the services they are performing or as otherwise required by law. We may also share certain Personal Information or Location Based Information with service providers in order to facilitate the operation of our Service. We may also share Personal Information or Location Based Information with service providers in order to allow them to use that information to obtain and provide us with additional information about you (including through the use of “prefill” services).

LikeNow or its agents or contractors may disclose Personal Information or Location Based Information if required to do so by law or in the good faith belief that such action is necessary to: (1) conform to the edicts of the law or comply with legal process; (2) protect and defend the rights or property of LikeNow Business Machines Incorporated or its agents or contractors; or (3) act in urgent circumstances to protect the personal safety of users of the Service or the public.

Finally, if LikeNow should ever merge with another organization, file for bankruptcy, or sell our assets, we may transfer the information you provide to us on through the Service to a third party or share your Personal Information to the company with which we enter into such transaction as a part of such transaction.
** Security of Your Information

We maintain physical, electronic, and procedural safeguards designed to protect Personal Information, and our systems are designed to protect Personal Information from unauthorized usage on shared computers in that users are required to log in through our applications.

Please keep in mind that whenever you voluntarily disclose Personal Information through public facing aspects of the Service, through e-mail, or in chat areas, that information can be collected and used by others. In short, by posting Personal Information online that is publicly accessible, you may receive unsolicited messages from other parties in return. We are not responsible for the security or privacy of any Personal Information you choose to submit in connection with these public features.

We may send an email or SMS to you at the email address or Phone Number you have provided to us in the event of a security breach. Depending on where you live, you may have a legal right to receive notice of a security breach in writing.
** Third-Party Websites, Services and Applications

Please be aware that other websites and services, including the websites of third parties that you connect with through our Website or Service, may collect personally identifiable information about you. This Privacy Policy does not cover the information practices of those third-party websites, services or applications. Additionally, certain Personal Information may be made available to third parties using our Application Programming Interface (“API”). Use of third party applications developed using our API are subject to the terms of use and privacy policies of such third party developers. You should be aware that such third party applications may expose user information.

We may use third-party services such as Google Analytics to help us understand how users use the Service and improve the ways in which we interact with users, including the refinement of interest-based ads displayed to users. Such services, including Google Analytics, may collect information about your use of the Service through cookies, advertising identifiers and other technologies. The collection and use of data by such third parties, including Google Analytics, is subject to their privacy policies.
** Access, Correction, and Deletion

To the extent provided by the law of your jurisdiction, you may have the right to (i) access certain Personal Information we maintain about you, (ii) request that we update or correct inaccuracies in that information, (iii) object to our use of your personal information, (iv) ask us to delete your personal information from our database and those of our service providers, and/or (v) receive equal service and price when exercising the preceding rights. To exercise these rights, please contact us as indicated in the How To Contact Us section of this Privacy Policy. If you are a California resident, please consult the section below for more information specific to your rights. To help protect your privacy and maintain security, we may take steps to verify your identity before granting you access to the information. To the extent permitted by applicable law, a charge may apply before we provide you with a copy of any of your Personal Information that we maintain.

Special Notice For California Residents

If you are a California resident, then you have certain rights under the California Consumer Privacy Act (“CCPA”) regarding your Personal Information. Access to Personal Information Rights. You have the right to request that we disclose certain information to you about our collection, use and disclosure of your Personal Information. This includes your right to request the specific pieces of Personal Information that we have collected about you.

Deletion Request Rights. You have the right to request that we delete any of your Personal Information that we collected from you and retained, subject to certain exceptions provided by law. To exercise your access or deletion request rights, please submit a verifiable consumer request to us as indicated in the How To Contact Us section of this Privacy Policy.

We will not discriminate against you for exercising any of your CCPA rights. Unless permitted by the CCPA, we will not deny you goods or services; charge you different prices or rates for goods or services; provide you a different level or quality of goods or services; or suggest that you may receive a different price or rate for goods or services or a different level or quality of goods or services.

Only you, or someone legally authorized to act on your behalf, may make a verifiable consumer request related to your Personal Information. You may only make a verifiable consumer request for access twice within a 12-month period. The verifiable consumer request must:

- Provide sufficient information that allows us to reasonably verify you are the person about whom we collected Personal Information or an authorized representative.
- Describe your request with sufficient detail that allows us to properly understand, evaluate, and respond to it. We cannot respond to your request or provide you with Personal Information if we cannot verify your identity or authority to make the request and confirm the Personal Information relates to you.

** How To Contact Us
If you have any questions about this Privacy Policy, or if you would like us to update information we have about you, change your preferences or exercise other applicable data protection rights, please contact us by e-mail at support@likenow.org
